import fs from "fs";
import path from "path";
import PDFDocument from "pdfkit";
import { env } from "../config/env.js";

const pdfDir = path.resolve("storage", "pdfs");

function ensurePdfDir() {
  fs.mkdirSync(pdfDir, { recursive: true });
}

export function sanitizePdfFilename(value) {
  return String(value).replace(/[^a-z0-9-_]/gi, "-").replace(/-+/g, "-").toLowerCase();
}

function writePdf(filename, draw) {
  ensurePdfDir();
  const safeFilename = sanitizePdfFilename(filename);
  const filePath = path.join(pdfDir, `${safeFilename}.pdf`);
  const doc = new PDFDocument({ margin: 48 });
  doc.pipe(fs.createWriteStream(filePath));
  draw(doc);
  doc.end();
  return `${env.pdfBaseUrl}/${safeFilename}.pdf`;
}

export function generateInvoicePdf(invoice, customer) {
  return writePdf(`invoice-${invoice.id}`, (doc) => {
    doc.fontSize(22).text("NxtBiz Invoice");
    doc.moveDown();
    doc.fontSize(12).text(`Invoice ID: ${invoice.id}`);
    doc.text(`Customer: ${customer?.name || "Unknown customer"}`);
    doc.text(`Due Date: ${invoice.dueDate?.toISOString?.().slice(0, 10) || invoice.dueDate}`);
    doc.text(`Amount Due: ${invoice.amount}`);
    doc.moveDown();
    doc.text("Generated by NxtBiz operations automation.");
  });
}

export function generateReportPdf(report) {
  return writePdf(`report-${report.id || report.title}`, (doc) => {
    doc.fontSize(22).text(report.title || "NxtBiz Report");
    doc.moveDown();
    doc.fontSize(12).text(report.summary || "No summary provided.");
    doc.moveDown();
    doc.text("Metrics");
    Object.entries(report.metrics || {}).forEach(([key, value]) => {
      doc.text(`${key}: ${value}`);
    });
    doc.moveDown();
    doc.text("Recommendations");
    (report.recommendations || []).forEach((item) => doc.text(`- ${item}`));
  });
}
